#!/bin/bash

# This script is a convenience script to start the Constellation registry server

function check_env_dir() {
    local name_env_dir=$1
    if [ -z ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir has not been set"
	exit 1
    fi

    if [ ! -d ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir does not represent a directory"
	exit 1
    fi
}

check_env_dir VECTORADD_DIR

BIN_DIR=$VECTORADD_DIR/bin

source $BIN_DIR/check_environment_variable.bash
check_env CONSTELLATION_PORT

source $BIN_DIR/create_class_path.bash

CLASSPATH=$(createClassPath $VECTORADD_DIR "lib/ipl-support-2.3.1.jar")

exec java -classpath $CLASSPATH \
     -Dgat.adapter.path \
     -Dibis.io.buffer.size=65536 \
     -Dibis.io.conversion.buffer.size=65536 \
     -Dibis.registry.central.server.connect.timeout=300 \
     -Dlog4j.configuration=file:"$VECTORADD_DIR"/log4j.properties \
     -Xmx256M \
     ibis.ipl.server.Server --events --port $CONSTELLATION_PORT

