#!/bin/bash

function check_env_dir() {
    local name_env_dir=$1
    if [ -z ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir has not been set"
	exit 1
    fi

    if [ ! -d ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir does not represent a directory"
	exit 1
    fi
}

check_env_dir ROW_IMPL_DIR
BIN_DIR=$ROW_IMPL_DIR/bin
source $BIN_DIR/check_environment_variable.bash

check_env CONSTELLATION_PORT

ruby $BIN_DIR/run-on-nodes.das5.rb \
     $ROW_IMPL_DIR \
     lib/btp.hd.cji.jar \
     btp.hd.cji.HeatDissipator \
     "$config_args" \
     "$@"
