#!/bin/bash

# This script can be used for running ibis applications on the local host.

JAVA_IO_TEMP_DIR=$HOME/.java_io_tmp

mkdir -p $JAVA_IO_TEMP_DIR 

java -classpath $CLASSPATH \
     -Djava.io.tmpdir=$JAVA_IO_TEMP_DIR \
     -Dibis.constellation.steal.delay=10 "$@" 2>&1
